version: '3.0'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/src/app # mount local working directory for live reload
      - /usr/src/app/node_modules 

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: backend
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8080:8080"

  # mongo:
  #   image: mongo:7.0
  #   container_name: mongo_db
  #   volumes:
  #     - mongodata:/data/db
  #   ports:
  #     - "27017:27017"