version: '3.0'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules 
      - ./frontend/.env:/usr/src/app/.env  # Mount .env into the frontend container


  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/.env:/app/.env  # Mount .env file into /app inside container
    environment:
      - SPRING_PROFILES_ACTIVE=prod